import React, { useEffect, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { useAuth } from '../context/AuthContext';
import Card from '../components/Card';

const Home = () => {
  const navigate = useNavigate();
  const { user } = useAuth();
  const [openFaq, setOpenFaq] = useState(null);

  useEffect(() => {
    // If user is logged in, redirect to their dashboard
    if (user) {
      navigate(`/${user.role}/dashboard`);
    }
  }, [user, navigate]);

  const toggleFaq = (index) => {
    setOpenFaq(openFaq === index ? null : index);
  };

  const roles = [
    {
      name: 'Organizer',
      role: 'organizer',
      description: 'Create and manage conferences, review submissions, and handle all organizational tasks.',
      icon: '🎯',
      color: 'from-blue-500 to-blue-600'
    },
    {
      name: 'Author',
      role: 'author',
      description: 'Discover conferences, submit research papers, and track your submission status.',
      icon: '✍️',
      color: 'from-green-500 to-green-600'
    },
    {
      name: 'Reviewer',
      role: 'reviewer',
      description: 'Review papers, provide feedback, and help maintain academic quality.',
      icon: '📝',
      color: 'from-purple-500 to-purple-600'
    },
    {
      name: 'Participant',
      role: 'participant',
      description: 'Register for conferences, attend sessions, and receive certificates.',
      icon: '👥',
      color: 'from-orange-500 to-orange-600'
    }
  ];

  const handleRoleClick = (role) => {
    navigate(`/login?role=${role}`);
  };

  const faqs = [
    {
      question: "What is the Conference Management System?",
      answer: "The CMS is a comprehensive platform designed to streamline the entire lifecycle of academic and professional conferences, from paper submission to certificate generation."
    },
    {
      question: "How do I register as an organizer?",
      answer: "Click on the Organizer role card, then register with your email and credentials. Once registered, you can create and manage conferences."
    },
    {
      question: "Can I have multiple roles?",
      answer: "Yes, you can register separate accounts for different roles or switch between roles based on your conference involvement."
    },
    {
      question: "How does the review process work?",
      answer: "Organizers assign papers to reviewers based on expertise. Reviewers can bid on papers, provide scores, and submit detailed feedback. Authors receive notifications at each stage."
    },
    {
      question: "Is the platform free to use?",
      answer: "Yes, the platform is currently free for all users. Organizers, authors, reviewers, and participants can use all features without any charges."
    },
    {
      question: "How are notifications sent?",
      answer: "Users receive email notifications for key events such as paper submissions, review assignments, status updates, and certificate availability."
    },
    {
      question: "Can an author submit multiple papers to the same conference?",
      answer: "Yes, authors can submit multiple papers to the same conference as long as each submission follows the conference guidelines and is uploaded separately."
    },
    {
      question: "Can a reviewer review papers outside their expertise?",
      answer: "By default, reviewers see papers matching their expertise, but they can choose to view and bid on other papers if needed."
    },
    {
      question: "Who can edit conference details?",
      answer: "Only organizers have permission to create, edit, and manage conference details, tracks, and reviewer assignments."
    },
    {
      question: "Can papers be updated after submission?",
      answer: "Only the primary author can re-upload or update the paper when revisions are requested. Co-authors have view-only access."
    },
    {
      question: "How are certificates generated?",
      answer: "Certificates are generated by organizers after conference completion and are made available for download in the participant and author dashboards."
    },
    {
      question: "What happens if a co-author does not have an account?",
      answer: "If a co-author does not have an account, they will receive email notifications and can create an account later to view the paper."
    },
    {
      question: "Can expired conferences be accessed?",
      answer: "Expired conferences are hidden from dashboards, but related submissions, reviews, and certificates remain accessible."
    },
    {
      question: "Is this platform suitable for both academic and industry conferences?",
      answer: "Yes, the system is designed to support academic, professional, and industry-level conferences with flexible workflows."
    }
  ];

  return (
    <div className="min-h-screen bg-gradient-to-br from-gray-50 to-gray-100">
      {/* Header */}
      <header className="bg-white shadow-sm">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-6">
          <h1 className="text-3xl font-bold text-gray-900">
            Conference Management System
          </h1>
          <p className="mt-2 text-gray-600">
            Your complete platform for academic and professional conference management
          </p>
        </div>
      </header>

      {/* Main Content */}
      <main className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-12">
        <div className="text-center mb-12">
          <h2 className="text-4xl font-bold text-gray-900 mb-4">
            Choose Your Role
          </h2>
          <p className="text-xl text-gray-600">
            Select your role to get started with conference management
          </p>
        </div>

        {/* Role Cards Grid */}
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
          {roles.map((roleItem) => (
            <Card
              key={roleItem.role}
              hoverable
              onClick={() => handleRoleClick(roleItem.role)}
              className="group"
            >
              <div className="flex flex-col items-center text-center h-full">
                {/* Icon with gradient background */}
                <div className={`w-20 h-20 rounded-full bg-gradient-to-br ${roleItem.color} flex items-center justify-center text-4xl mb-4 group-hover:scale-110 transition-transform duration-200`}>
                  {roleItem.icon}
                </div>

                {/* Role Name */}
                <h3 className="text-2xl font-bold text-gray-900 mb-3">
                  {roleItem.name}
                </h3>

                {/* Description */}
                <p className="text-gray-600 flex-grow">
                  {roleItem.description}
                </p>

                {/* CTA */}
                <div className={`mt-6 px-4 py-2 rounded-lg bg-gradient-to-r ${roleItem.color} text-white font-medium group-hover:shadow-lg transition-shadow duration-200`}>
                  Get Started →
                </div>
              </div>
            </Card>
          ))}
        </div>

        {/* Features Section */}
        <div className="mt-20">
          <h3 className="text-2xl font-bold text-center text-gray-900 mb-10">
            Platform Features
          </h3>
          <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
            <div className="text-center">
              <div className="text-4xl mb-3">🚀</div>
              <h4 className="text-lg font-semibold text-gray-900 mb-2">
                Easy to Use
              </h4>
              <p className="text-gray-600">
                Intuitive card-based interface for seamless navigation and management
              </p>
            </div>
            <div className="text-center">
              <div className="text-4xl mb-3">🔒</div>
              <h4 className="text-lg font-semibold text-gray-900 mb-2">
                Secure & Reliable
              </h4>
              <p className="text-gray-600">
                Role-based access control and JWT authentication for data security
              </p>
            </div>
            <div className="text-center">
              <div className="text-4xl mb-3">⚡</div>
              <h4 className="text-lg font-semibold text-gray-900 mb-2">
                Full Lifecycle
              </h4>
              <p className="text-gray-600">
                Complete conference management from submission to certification
              </p>
            </div>
          </div>
        </div>

        {/* FAQ Section */}
        <div className="mt-20 max-w-4xl mx-auto">
          <h3 className="text-3xl font-bold text-center text-gray-900 mb-10">
            Frequently Asked Questions
          </h3>
          <div className="space-y-4">
            {faqs.map((faq, index) => (
              <div
                key={index}
                className="bg-white rounded-lg shadow-sm border border-gray-200 overflow-hidden transition-all duration-200"
              >
                <button
                  onClick={() => toggleFaq(index)}
                  className="w-full px-6 py-4 text-left flex items-center justify-between hover:bg-gray-50 transition-colors duration-200"
                >
                  <span className="font-semibold text-gray-900 pr-8">
                    {faq.question}
                  </span>
                  <svg
                    className={`w-5 h-5 text-gray-500 transform transition-transform duration-200 flex-shrink-0 ${
                      openFaq === index ? 'rotate-180' : ''
                    }`}
                    fill="none"
                    stroke="currentColor"
                    viewBox="0 0 24 24"
                  >
                    <path
                      strokeLinecap="round"
                      strokeLinejoin="round"
                      strokeWidth={2}
                      d="M19 9l-7 7-7-7"
                    />
                  </svg>
                </button>
                <div
                  className={`overflow-hidden transition-all duration-200 ${
                    openFaq === index ? 'max-h-96' : 'max-h-0'
                  }`}
                >
                  <div className="px-6 py-4 bg-gray-50 border-t border-gray-200">
                    <p className="text-gray-700 leading-relaxed">
                      {faq.answer}
                    </p>
                  </div>
                </div>
              </div>
            ))}
          </div>
        </div>
      </main>

      {/* Footer */}
      <footer className="bg-white border-t mt-20">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
          <p className="text-center text-gray-600">
            © 2025 Conference Management System. All rights reserved.
          </p>
        </div>
      </footer>
    </div>
  );
};

export default Home;
